age <- c(1, 3, 5, 2, 11, 9, 3, 12, 3)
weight <- c(4.4, 5.3, 7.2, 5.2, 8.5, 7.3, 6.0, 10.4, 10.2)
mean(weight)
mad(weight)
cor(age, weight)
plot(age, weight)
getwd()
help.search("Introduction to R")
help.start()
library()
library(vcd)
??vcd
data()
RSiteSearch('vcd')
apropos('vcd', mode = function)
??apropos
Arthritis
example(Arthritis)
plot(Arthritis)
apropos("vcd", mode = "function")
apropos("vcd")